version: '3.4'

services:
  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./keys:/etc/vmdeployment/cert
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./proxy/proxy_config:/etc/nginx/nginx.conf
      - ./keys:/etc/vmdeployment/cert
      - ./proxy/logs:/var/log/nginx
      - ./proxy/ssl-dhparams.pem:/etc/vmdeployment/ssl-dhparams.pem
    ports:
      - 443:443
    links:
      - backend