#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN apt-get update
RUN apt-get install -y openssh-client
RUN apt-get install -y openssl

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./backend/backend.csproj"
RUN dotnet restore "./OpenNebula/OpenNebula.csproj"
WORKDIR "/src/"
RUN dotnet build "./backend/backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./backend/backend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --chown=1111:1111 --from=publish /app/publish .
COPY --chown=1111:1111 --from=build /src/backend/appsettings.json .
USER 1111:1111
ENTRYPOINT ["dotnet", "backend.dll"]
