#Build
FROM node:14 as build
WORKDIR /src
COPY ./front-end/package*.json ./
RUN npm install
COPY ./front-end/* ./
RUN ls -la .
RUN npm run build

#Run
FROM nginx:stable-alpine as prod
COPY --from=build /src/dist /app
EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
