#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./backend/backend.csproj"
RUN dotnet restore "./OpenNebula/OpenNebula.csproj"
WORKDIR "/src/"
RUN dotnet build "./backend/backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./backend/backend.csproj" -c Release -o /app/publish

FROM base AS final
RUN apt-get update
RUN apt-get install -y openssh-client
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=build /src/backend/appsettings.json .
ENTRYPOINT ["dotnet", "backend.dll"]
