version "3.9"
services:
  proxy:
    image: nginx:stable-alpine
    volumes: 
      - ./proxy/config:/etc/nginx/conf.d
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./cert/conf:/etc/letsencrypt
      - ./cert/www:/var/www/certbot
