name: Main-Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'Server/front-end/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Server/front-end/**'

jobs:
  docker-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: ./.github/actions/build-and-push
      with:
        username: Hounsvad
        token: ghcr.io/hounsvad/scalableteaching-frontend
        version: latest
        dockerfile: Server/Dockerfile-FrontendAndProxy
        context: ./Server
      secrets:
        PACKAGE_KEY: ${{ secrets.PACKAGE_KEY }}