name: Docker-Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.PACKAGE_KEY}}" | docker login https://ghcr.io -u hounsvad --password-stdin
      
      - name: Build image
        run: |
          docker buildx build --push -t ghcr.io/hounsvad/scalableteaching-backend -f ./Server/Dockerfile-Backend ./Server
  docker-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.PACKAGE_KEY}}" | docker login https://ghcr.io -u hounsvad --password-stdin
      
      - name: Build image
        run: |
          docker buildx build --push -t ghcr.io/hounsvad/scalableteaching-frontend -f ./Server/Dockerfile-FrontendAndProxy ./Server

