name: Main-Backend

on:
  push:
    branches:
      - main
    paths:
      - 'Server/backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Server/backend/**'

jobs:
  docker-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: ./.github/actions/build-and-push/action.yml
      with:
        username: 'Hounsvad'
        token: 'ghcr.io/hounsvad/scalableteaching-backend'
        version: 'latest'
        dockerfile: 'Server/Dockerfile-Backend'
        context: './Server'